In [ ]:
import matplotlib.pyplot as plt

# Data for plotting
x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]

# Create a figure and axis
fig, ax = plt.subplots()

# Plot the data
ax.plot(x, y)

# Add labels and title
ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_title('My Line Graph')

# Show the plot
plt.show()


In [8]:
import numpy as np
# np.array([[object1], [objeto2], object3]]) Manualmente
primeiro_array = np.array([1, 2, 3, 4, 5, 6, 7]) 

print(primeiro_array)
print(type(primeiro_array))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [11]:
matriz_array = np.array([[1, 2, 3, 4, 5, 6, 7],[3, 4, 5, 6, 7, 8, 9], 
                        [4, 6, 5, 7, 8, 9, 7]]) 

print(matriz_array)

[[1 2 3 4 5 6 7]
 [3 4 5 6 7 8 9]
 [4 6 5 7 8 9 7]]


In [12]:
#np.zeros()
# 5 dimensões 3x6
zero_array = np.zeros(shape = (5,3,6))

print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [13]:
#np.ones()

um_array = np.ones((2,3))

print(um_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
#np.empty() sem valores vazios

vazio = np.empty(4)

print(vazio)

[ 10.         246.98222222  32.125      260.98222222]


In [23]:
#np.arange([sart], stop, [step])

arr = np.arange(0,11,5)
rr = np.arange
print(arr)

[ 0  5 10]


In [29]:
#np.linspace(start, stop, num=tamanho, endpoint=False/True, retsetp=True) linear

linear_array = np.linspace(0,100, num=20, endpoint=True)

print(linear_array)

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]


In [43]:
# Gerando números aleatórios

from numpy.random import default_rng

rng = default_rng()

aleatorio = rng.integers(100, size= (2,4))

print(aleatorio)

[[50 43  6 52]
 [85  8 12  0]]


In [31]:
# Shape
print(zero_array.shape)

#Tamanho
print(zero_array.size)

#dimensões
print(zero_array.ndim)

(5, 3, 6)
90
3


In [34]:
#Acrescentando dimensões 
a = np.arange(1, 5)

print(a.ndim)

a2 = a[np.newaxis,:]

1


In [36]:
# Concatenação

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))

print(c)

[1 2 3 4 5 6]


In [39]:
# Consultando dados

a = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

maior_8 = a[a>=8]

print(maior_8)

[ 8  9 10 11 12]


In [41]:
#Operações

a = np.array([1, 2, 3])

print(a.sum())
print(a.max())
print(a.mean())

6
3
2.0


In [11]:
# aplicações 
from time import process_time
from numpy.random import default_rng


rng = default_rng()
a =  rng.integers(10,100, 10000000)
b =  rng.integers(10,100, 10000000)

t1 = process_time()

c = a*b

t2 = process_time()

print(t2-t1)

0.03125


In [12]:
list_a =  list(rng.integers(10,100, 10000000))
list_b =  list(rng.integers(10,100, 10000000))
c2 = []
t11 = process_time()

for i in range(len(list_a)):
    c2.append(list_a[i]*list_b[i])

t22 = process_time()

print(t22-t11)

2.9375
